// Generated by cbindgen from bindings/ffi. Do not edit by hand.
// Out-pointers require valid writable storage; alignment is not required.
// Object frees return status and wait for an active operation on that handle.
// Copy curvy_last_error before the next fallible call, including successful calls.
// All C string inputs must be NUL terminated within their readable allocation.


#ifndef CURVY_FFI_H
#define CURVY_FFI_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef enum CurvyStatus {
  CurvyStatus_Ok = 0,
  /**
   * A Rust-side error; call `curvy_last_error` for the message.
   */
  CurvyStatus_Error = 1,
  /**
   * A null pointer or non-UTF-8 string arrived from the caller.
   */
  CurvyStatus_InvalidArgument = 2,
  /**
   * A handle was unknown or already freed.
   */
  CurvyStatus_InvalidHandle = 3,
  /**
   * Rust panicked; call `curvy_last_error`.
   */
  CurvyStatus_Panic = 4,
} CurvyStatus;

/**
 * An owned byte buffer handed to the caller. Free with [`curvy_bytes_free`].
 */
typedef struct CurvyBytes {
  uint8_t *ptr;
  uintptr_t len;
} CurvyBytes;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Returns the boundary version shared with `curvy-wasm`.
 */
enum CurvyStatus curvy_version(char **out);

/**
 * Verifies that the native library is linked. Safe to call more than once.
 */
enum CurvyStatus curvy_init(void);

/**
 * # Safety
 * `inputs_json` must be a NUL-terminated JSON array of decimal strings.
 */
enum CurvyStatus curvy_poseidon(const char *inputs_json, char **out);

/**
 * Hashes raw 256-bit decimal inputs without field reduction.
 *
 * # Safety
 * `inputs_json` must be a NUL-terminated JSON array of decimal strings.
 */
enum CurvyStatus curvy_sha256_bigint(const char *inputs_json, char **out);

/**
 * # Safety
 * All pointers must be NUL-terminated UTF-8 decimal strings.
 */
enum CurvyStatus curvy_owner_hash(const char *pub_x,
                                  const char *pub_y,
                                  const char *shared_secret,
                                  char **out);

/**
 * # Safety
 * All pointers must be NUL-terminated UTF-8 decimal strings.
 */
enum CurvyStatus curvy_note_id(const char *owner_hash,
                               const char *amount,
                               const char *token,
                               char **out);

/**
 * # Safety
 * All pointers must be NUL-terminated UTF-8 decimal strings.
 */
enum CurvyStatus curvy_nullifier(const char *shared_secret,
                                 const char *pub_x,
                                 const char *pub_y,
                                 char **out);

/**
 * `[x, y]` from a hex private key.
 *
 * # Safety
 * `private_key_hex` must be a NUL-terminated UTF-8 string.
 */
enum CurvyStatus curvy_pub_from_private_key(const char *private_key_hex, char **out);

/**
 * Returns `[x, y] = scalar * Base8` without seed derivation.
 *
 * # Safety
 * `scalar` must be a NUL-terminated UTF-8 decimal string.
 */
enum CurvyStatus curvy_pub_from_scalar(const char *scalar, char **out);

/**
 * Returns `R = scalar * Base8` as `[x, y]`.
 *
 * # Safety
 * `scalar` must be a NUL-terminated UTF-8 decimal string.
 */
enum CurvyStatus curvy_ephemeral_pub_key(const char *scalar, char **out);

/**
 * EdDSA-Poseidon signature `[R8.x, R8.y, S]` from a hex private key.
 *
 * # Safety
 * Both pointers must be NUL-terminated UTF-8 strings.
 */
enum CurvyStatus curvy_sign(const char *message, const char *private_key_hex, char **out);

/**
 * Direct-scalar Curvy signature `[R8.x, R8.y, S]`.
 *
 * # Safety
 * Both pointers must be NUL-terminated UTF-8 decimal strings.
 */
enum CurvyStatus curvy_sign_with_scalar(const char *message, const char *scalar, char **out);

/**
 * Verify a scalar-native Curvy signature.
 *
 * Malformed or non-canonical inputs are an error; a well-formed but invalid
 * signature writes `0` and returns `Ok`. Conflating the two would let a
 * verification failure look like a parse failure.
 *
 * # Safety
 * All pointers must be NUL-terminated UTF-8 decimal strings.
 */
enum CurvyStatus curvy_verify_scalar_signature(const char *message,
                                               const char *public_x,
                                               const char *public_y,
                                               const char *r8_x,
                                               const char *r8_y,
                                               const char *s,
                                               int *out);

/**
 * Maps `(amount, token)` to `[encryptedAmount, encryptedToken]`.
 *
 * # Safety
 * All pointers must be NUL-terminated UTF-8 decimal strings.
 */
enum CurvyStatus curvy_encrypt_amount_token(const char *amount,
                                            const char *token,
                                            const char *shared_secret,
                                            const char *ephemeral_key_x,
                                            const char *ephemeral_key_y,
                                            char **out);

/**
 * Maps `(encryptedAmount, encryptedToken)` to `[amount, token]`.
 *
 * # Safety
 * All pointers must be NUL-terminated UTF-8 decimal strings.
 */
enum CurvyStatus curvy_decrypt_amount_token(const char *encrypted_amount,
                                            const char *encrypted_token,
                                            const char *shared_secret,
                                            const char *ephemeral_key_x,
                                            const char *ephemeral_key_y,
                                            char **out);

/**
 * Fresh random meta-keys `[k, v, K, V]`.
 */
enum CurvyStatus curvy_new_meta(char **out);

/**
 * Public meta-keys `[k, v, K, V]` for the given private spend/view keys.
 *
 * # Safety
 * Both pointers must be NUL-terminated UTF-8 strings.
 */
enum CurvyStatus curvy_get_meta(const char *k, const char *v, char **out);

/**
 * Announces a payment to `(K, V)` as `[r, R, viewTag, spendingPubKey]`.
 *
 * # Safety
 * Both pointers must be NUL-terminated UTF-8 strings.
 */
enum CurvyStatus curvy_send(const char *big_k, const char *big_v, char **out);

/**
 * Returns `[index, spendingPubKey, spendingPrivKey, ...]`.
 *
 * Matches are candidates because the one-byte view tag admits false positives.
 *
 * # Safety
 * `k`/`v` must be NUL-terminated strings; `rs_json`/`view_tags_json` must be
 * NUL-terminated JSON arrays of strings.
 */
enum CurvyStatus curvy_scan(const char *k,
                            const char *v,
                            const char *rs_json,
                            const char *view_tags_json,
                            char **out);

/**
 * Returns `[index, spendingPubKey, ...]` for view-only scanning.
 *
 * # Safety
 * See [`curvy_scan`].
 */
enum CurvyStatus curvy_viewer_scan(const char *v,
                                   const char *big_k,
                                   const char *rs_json,
                                   const char *view_tags_json,
                                   char **out);

/**
 * # Safety
 * `point` must be a NUL-terminated UTF-8 string.
 */
int curvy_is_valid_bn254_point(const char *point);

/**
 * # Safety
 * `point` must be a NUL-terminated UTF-8 string.
 */
int curvy_is_valid_secp256k1_point(const char *point);

/**
 * Returns this thread's last error, or null. Copy it before the next fallible call.
 *
 * # Safety
 * The returned pointer is owned by Rust and must not be freed by the caller.
 */
const char *curvy_last_error(void);

/**
 * # Safety
 * `ptr` must have come from this library and not been freed already.
 */
void curvy_string_free(char *ptr);

/**
 * # Safety
 * `bytes` must have come from this library and not been freed already.
 *
 * A zero length means no allocation was made.
 */
void curvy_bytes_free(struct CurvyBytes bytes);

/**
 * Imports a 32-byte seed. The caller owns the input and may wipe it after return.
 * # Safety
 * `seed` is readable for `len` bytes; `out` points to writable handle storage.
 */
enum CurvyStatus curvy_seed_signer_new(const uint8_t *seed, uintptr_t len, uint64_t *out);

/**
 * Imports a canonical nonzero 32-byte little-endian scalar.
 * The caller owns the input and may wipe it after return.
 * # Safety
 * `scalar` is readable for `len` bytes; `out` points to writable handle storage.
 */
enum CurvyStatus curvy_scalar_signer_new(const uint8_t *scalar, uintptr_t len, uint64_t *out);

/**
 * Erases and frees an owned seed signer after its active operation completes.
 */
enum CurvyStatus curvy_seed_signer_free(uint64_t handle);

/**
 * Erases and frees an owned scalar signer after its active operation completes.
 */
enum CurvyStatus curvy_scalar_signer_free(uint64_t handle);

/**
 * Returns `[x, y]` as a JSON array of decimal strings.
 * # Safety
 * `out` points to writable string-pointer storage. Free output with `curvy_string_free`.
 */
enum CurvyStatus curvy_seed_signer_public_key(uint64_t handle, char **out);

/**
 * Returns `[x, y]` as a JSON array of decimal strings.
 * # Safety
 * `out` points to writable string-pointer storage. Free output with `curvy_string_free`.
 */
enum CurvyStatus curvy_scalar_signer_public_key(uint64_t handle, char **out);

/**
 * Signs an unsigned decimal message below `2^256`, returning `[R8.x, R8.y, S]` as JSON.
 * # Safety
 * `message` is NUL-terminated UTF-8; `out` is writable string-pointer storage.
 * Free output with `curvy_string_free`.
 */
enum CurvyStatus curvy_seed_signer_sign(uint64_t handle, const char *message, char **out);

/**
 * Signs a canonical decimal BN254 field message, returning `[R8.x, R8.y, S]` as JSON.
 * # Safety
 * `message` is NUL-terminated UTF-8; `out` is writable string-pointer storage.
 * Free output with `curvy_string_free`.
 */
enum CurvyStatus curvy_scalar_signer_sign(uint64_t handle, const char *message, char **out);

/**
 * Returns `[x, y]` for a raw 32-byte little-endian scalar, including zero.
 * # Safety
 * `scalar` is readable for `len` bytes; `out` is writable string-pointer storage.
 * Free output with `curvy_string_free`.
 */
enum CurvyStatus curvy_ephemeral_pub_key_bytes(const uint8_t *scalar, uintptr_t len, char **out);

/**
 * Selects client limits when false and batch-prover limits when true.
 *
 * # Safety
 * `graph`/`len` must describe a readable region; `expected_sha256` must be a
 * NUL-terminated 64-character hex string.
 */
enum CurvyStatus curvy_witness_graph_new(const uint8_t *graph,
                                         uintptr_t len,
                                         const char *expected_sha256,
                                         bool batch_profile,
                                         uint64_t *out);

enum CurvyStatus curvy_witness_graph_free(uint64_t handle);

enum CurvyStatus curvy_witness_graph_assignment_size(uint64_t handle, uint32_t *out);

/**
 * Evaluate the graph and return the assignment as a JSON array of decimal
 * strings.
 *
 * # Safety
 * `input_json` must be a NUL-terminated UTF-8 JSON string.
 */
enum CurvyStatus curvy_witness_graph_calculate(uint64_t handle, const char *input_json, char **out);

/**
 * Evaluate the graph and return concatenated canonical 32-byte big-endian
 * assignment field elements.
 *
 * # Safety
 * `input_json` must be a NUL-terminated UTF-8 JSON string.
 */
enum CurvyStatus curvy_witness_graph_calculate_packed(uint64_t handle,
                                                      const char *input_json,
                                                      struct CurvyBytes *out);

/**
 * # Safety
 * `zkey`/`len` must describe a readable region; `expected_sha256` must be a
 * NUL-terminated 64-character hex string.
 */
enum CurvyStatus curvy_prover_new(const uint8_t *zkey,
                                  uintptr_t len,
                                  const char *expected_sha256,
                                  uint64_t *out);

enum CurvyStatus curvy_prover_free(uint64_t handle);

enum CurvyStatus curvy_prover_num_constraints(uint64_t handle, uint32_t *out);

enum CurvyStatus curvy_prover_num_public(uint64_t handle, uint32_t *out);

/**
 * Prove from a serialised `.wtns` witness.
 *
 * # Safety
 * `wtns`/`len` must describe a readable region.
 */
enum CurvyStatus curvy_prover_prove(uint64_t handle,
                                    const uint8_t *wtns,
                                    uintptr_t len,
                                    char **out);

/**
 * # Safety
 * Both buffer pointers must describe readable regions; both sha256 pointers
 * must be NUL-terminated 64-character hex strings.
 */
enum CurvyStatus curvy_resident_prover_new(const uint8_t *zkey,
                                           uintptr_t zkey_len,
                                           const char *expected_zkey_sha256,
                                           const uint8_t *graph,
                                           uintptr_t graph_len,
                                           const char *expected_graph_sha256,
                                           uint64_t *out);

enum CurvyStatus curvy_resident_prover_free(uint64_t handle);

/**
 * Compile an authenticated witness graph to SAGE for resident proving.
 *
 * # Safety
 * Buffer pointers must describe readable regions; hashes must be NUL-terminated
 * hex strings. `out` must be writable. Client artifact limits apply.
 */
enum CurvyStatus curvy_resident_prover_new_sage(const uint8_t *zkey,
                                                uintptr_t zkey_len,
                                                const char *expected_zkey_sha256,
                                                const uint8_t *graph,
                                                uintptr_t graph_len,
                                                const char *expected_graph_sha256,
                                                uint64_t *out);

/**
 * Load a compiled SAGE cache pinned independently from its source graph.
 * The original graph file is unnecessary, but its trusted digest is required.
 *
 * # Safety
 * Buffer pointers must describe readable regions; all three hashes must be
 * NUL-terminated hex strings. `out` must be writable. Client limits apply.
 */
enum CurvyStatus curvy_resident_prover_new_compiled_sage(const uint8_t *zkey,
                                                         uintptr_t zkey_len,
                                                         const char *expected_zkey_sha256,
                                                         const uint8_t *program,
                                                         uintptr_t program_len,
                                                         const char *expected_program_sha256,
                                                         const char *expected_graph_sha256,
                                                         uint64_t *out);

enum CurvyStatus curvy_resident_prover_num_constraints(uint64_t handle, uint32_t *out);

enum CurvyStatus curvy_resident_prover_num_public(uint64_t handle, uint32_t *out);

/**
 * Returns the stable developer-facing mode string (`resident`).
 *
 * # Safety
 * `out` must be writable and the returned string must be released with
 * `curvy_string_free`.
 */
enum CurvyStatus curvy_resident_prover_mode(uint64_t handle, char **out);

/**
 * Returns the architecture profile string (`HAWK`).
 *
 * # Safety
 * `out` must be writable and the returned string must be released with
 * `curvy_string_free`.
 */
enum CurvyStatus curvy_resident_prover_profile(uint64_t handle, char **out);

/**
 * Returns the SHA-256 of the loaded key's verifying key as 64 lowercase hex
 * characters. Compare it against the deployed verifier before submitting
 * proofs; the zkey digest pins the artifact, this pins the verifier.
 *
 * # Safety
 * `out` must be writable and the returned string must be released with
 * `curvy_string_free`.
 */
enum CurvyStatus curvy_resident_prover_verifying_key_digest(uint64_t handle, char **out);

/**
 * Calculates, proves, and self-verifies without exporting the witness.
 *
 * # Safety
 * `input_json` must be a NUL-terminated UTF-8 JSON string.
 */
enum CurvyStatus curvy_resident_prover_prove(uint64_t handle, const char *input_json, char **out);

uint32_t curvy_notes_tree_depth(void);

uint32_t curvy_notes_tree_version(void);

uint32_t curvy_notes_shard_height(void);

uint32_t curvy_notes_shard_size(void);

/**
 * # Safety
 * All buffer pointers must describe readable regions of the given lengths.
 */
enum CurvyStatus curvy_verify_merkle_proof(const uint8_t *leaf,
                                           uintptr_t leaf_len,
                                           uint32_t index,
                                           const uint8_t *siblings,
                                           uintptr_t siblings_len,
                                           const uint8_t *root,
                                           uintptr_t root_len,
                                           int *out);

enum CurvyStatus curvy_proof_free(uint64_t handle);

enum CurvyStatus curvy_proof_index(uint64_t handle, uint32_t *out);

enum CurvyStatus curvy_proof_leaf(uint64_t handle, struct CurvyBytes *out);

enum CurvyStatus curvy_proof_root(uint64_t handle, struct CurvyBytes *out);

enum CurvyStatus curvy_proof_siblings(uint64_t handle, struct CurvyBytes *out);

enum CurvyStatus curvy_merkle_new(uint32_t depth, uint64_t *out);

/**
 * # Safety
 * `packed_leaves`/`len` must describe a readable region.
 */
enum CurvyStatus curvy_merkle_from_leaves(uint32_t depth,
                                          const uint8_t *packed_leaves,
                                          uintptr_t len,
                                          uint64_t *out);

enum CurvyStatus curvy_merkle_free(uint64_t handle);

enum CurvyStatus curvy_merkle_depth(uint64_t handle, uint32_t *out);

enum CurvyStatus curvy_merkle_leaf_count(uint64_t handle, uint32_t *out);

enum CurvyStatus curvy_merkle_root(uint64_t handle, struct CurvyBytes *out);

enum CurvyStatus curvy_merkle_leaves(uint64_t handle, struct CurvyBytes *out);

/**
 * # Safety
 * `leaf`/`len` must describe a readable region.
 */
enum CurvyStatus curvy_merkle_insert(uint64_t handle,
                                     const uint8_t *leaf,
                                     uintptr_t len,
                                     uint32_t *out);

/**
 * # Safety
 * `packed_leaves`/`len` must describe a readable region.
 */
enum CurvyStatus curvy_merkle_insert_many(uint64_t handle,
                                          const uint8_t *packed_leaves,
                                          uintptr_t len);

/**
 * Writes `-1` when the leaf is absent.
 *
 * # Safety
 * `leaf`/`len` must describe a readable region.
 */
enum CurvyStatus curvy_merkle_get_index(uint64_t handle,
                                        const uint8_t *leaf,
                                        uintptr_t len,
                                        int64_t *out);

enum CurvyStatus curvy_merkle_truncate(uint64_t handle, uint32_t leaf_count);

/**
 * # Safety
 * `leaf`/`len` must describe a readable region.
 */
enum CurvyStatus curvy_merkle_proof(uint64_t handle,
                                    const uint8_t *leaf,
                                    uintptr_t len,
                                    uint64_t *out);

enum CurvyStatus curvy_merkle_proof_at(uint64_t handle, uint32_t index, uint64_t *out);

enum CurvyStatus curvy_ordered_new(uint32_t depth, uint64_t *out);

/**
 * # Safety
 * `packed_leaves`/`len` must describe a readable region.
 */
enum CurvyStatus curvy_ordered_from_leaves(uint32_t depth,
                                           const uint8_t *packed_leaves,
                                           uintptr_t len,
                                           uint64_t *out);

enum CurvyStatus curvy_ordered_free(uint64_t handle);

enum CurvyStatus curvy_ordered_depth(uint64_t handle, uint32_t *out);

enum CurvyStatus curvy_ordered_leaf_count(uint64_t handle, uint32_t *out);

enum CurvyStatus curvy_ordered_root(uint64_t handle, struct CurvyBytes *out);

/**
 * # Safety
 * `leaf`/`len` must describe a readable region.
 */
enum CurvyStatus curvy_ordered_insert(uint64_t handle,
                                      const uint8_t *leaf,
                                      uintptr_t len,
                                      uint32_t *out);

/**
 * # Safety
 * `packed_leaves`/`len` must describe a readable region.
 */
enum CurvyStatus curvy_ordered_insert_many(uint64_t handle,
                                           const uint8_t *packed_leaves,
                                           uintptr_t len);

enum CurvyStatus curvy_ordered_proof_at(uint64_t handle, uint32_t index, uint64_t *out);

enum CurvyStatus curvy_sharded_new(uint32_t depth, uint32_t shard_height, uint64_t *out);

/**
 * # Safety
 * `snapshot`/`len` must describe a readable region.
 */
enum CurvyStatus curvy_sharded_restore(const uint8_t *snapshot, uintptr_t len, uint64_t *out);

/**
 * # Safety
 * Both buffer pointers must describe readable regions of the given lengths.
 */
enum CurvyStatus curvy_sharded_restore_parts(uint32_t depth,
                                             uint32_t shard_height,
                                             const uint8_t *completed_roots,
                                             uintptr_t completed_roots_len,
                                             const uint8_t *live_leaves,
                                             uintptr_t live_leaves_len,
                                             uint64_t *out);

enum CurvyStatus curvy_sharded_free(uint64_t handle);

enum CurvyStatus curvy_sharded_depth(uint64_t handle, uint32_t *out);

enum CurvyStatus curvy_sharded_leaf_count(uint64_t handle, uint32_t *out);

enum CurvyStatus curvy_sharded_shard_height(uint64_t handle, uint32_t *out);

enum CurvyStatus curvy_sharded_shard_size(uint64_t handle, uint32_t *out);

enum CurvyStatus curvy_sharded_completed_shard_count(uint64_t handle, uint32_t *out);

enum CurvyStatus curvy_sharded_owned_note_count(uint64_t handle, uint32_t *out);

enum CurvyStatus curvy_sharded_root(uint64_t handle, struct CurvyBytes *out);

enum CurvyStatus curvy_sharded_snapshot(uint64_t handle, struct CurvyBytes *out);

enum CurvyStatus curvy_sharded_completed_shard_roots(uint64_t handle, struct CurvyBytes *out);

enum CurvyStatus curvy_sharded_completed_shard_root(uint64_t handle,
                                                    uint32_t shard_index,
                                                    struct CurvyBytes *out);

enum CurvyStatus curvy_sharded_live_leaves(uint64_t handle, struct CurvyBytes *out);

/**
 * # Safety
 * `note_id`/`len` must describe a readable region.
 */
enum CurvyStatus curvy_sharded_append(uint64_t handle, const uint8_t *note_id, uintptr_t len);

/**
 * # Safety
 * `packed_note_ids`/`len` must describe a readable region.
 */
enum CurvyStatus curvy_sharded_append_many(uint64_t handle,
                                           const uint8_t *packed_note_ids,
                                           uintptr_t len);

/**
 * # Safety
 * `note_id`/`len` must describe a readable region.
 */
enum CurvyStatus curvy_sharded_mark_owned(uint64_t handle,
                                          const uint8_t *note_id,
                                          uintptr_t len,
                                          uint32_t leaf_index);

/**
 * # Safety
 * `note_id`/`len` must describe a readable region.
 */
enum CurvyStatus curvy_sharded_unmark_owned(uint64_t handle,
                                            const uint8_t *note_id,
                                            uintptr_t len,
                                            int *out);

/**
 * # Safety
 * Both buffer pointers must describe readable regions of the given lengths.
 */
enum CurvyStatus curvy_sharded_adopt_frozen_witness(uint64_t handle,
                                                    const uint8_t *note_id,
                                                    uintptr_t note_id_len,
                                                    uint32_t leaf_index,
                                                    const uint8_t *siblings,
                                                    uintptr_t siblings_len);

enum CurvyStatus curvy_sharded_rewind_live_to(uint64_t handle,
                                              uint32_t leaf_count,
                                              struct CurvyBytes *out);

/**
 * # Safety
 * `note_id`/`len` must describe a readable region.
 */
enum CurvyStatus curvy_sharded_witness(uint64_t handle,
                                       const uint8_t *note_id,
                                       uintptr_t len,
                                       uint64_t *out);

enum CurvyStatus curvy_sharded_owned_notes(uint64_t handle, struct CurvyBytes *out);

enum CurvyStatus curvy_sharded_drain_dirty_owned_notes(uint64_t handle, struct CurvyBytes *out);

enum CurvyStatus curvy_frontier_new(uint32_t depth, uint32_t shard_height, uint64_t *out);

enum CurvyStatus curvy_frontier_production(uint64_t *out);

/**
 * # Safety
 * `snapshot`/`len` must describe a readable region.
 */
enum CurvyStatus curvy_frontier_restore(const uint8_t *snapshot, uintptr_t len, uint64_t *out);

enum CurvyStatus curvy_frontier_free(uint64_t handle);

enum CurvyStatus curvy_frontier_depth(uint64_t handle, uint32_t *out);

enum CurvyStatus curvy_frontier_leaf_count(uint64_t handle, uint32_t *out);

enum CurvyStatus curvy_frontier_shard_count(uint64_t handle, uint32_t *out);

enum CurvyStatus curvy_frontier_shard_height(uint64_t handle, uint32_t *out);

enum CurvyStatus curvy_frontier_shard_size(uint64_t handle, uint32_t *out);

enum CurvyStatus curvy_frontier_root(uint64_t handle, struct CurvyBytes *out);

enum CurvyStatus curvy_frontier_snapshot(uint64_t handle, struct CurvyBytes *out);

/**
 * One append, packed as
 * `[u32 leafIndex][u8 hasCompletedShard][u32 shardIndex][32B shardRoot]`.
 *
 * # Safety
 * `leaf`/`len` must describe a readable region.
 */
enum CurvyStatus curvy_frontier_append(uint64_t handle,
                                       const uint8_t *leaf,
                                       uintptr_t len,
                                       struct CurvyBytes *out);

/**
 * Bulk append; returns the completed shards as
 * `[u32 count]` then per shard `[u32 shardIndex][32B root]`.
 *
 * # Safety
 * `packed_leaves`/`len` must describe a readable region.
 */
enum CurvyStatus curvy_frontier_append_many(uint64_t handle,
                                            const uint8_t *packed_leaves,
                                            uintptr_t len,
                                            struct CurvyBytes *out);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* CURVY_FFI_H */
