/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Native indexed Poseidon tree used by backend services. The tree itself is a
 * core primitive; `build_pending_commitment` is the canonical adapter for the
 * currently deployed pending-notes-commitment circuit input.
 */
export declare class IndexedMerkleTree {
  constructor(depth: number, leavesJson: string)
  /**
   * Construct directly from concatenated canonical 32-byte big-endian
   * BN254 field elements, avoiding decimal strings and a JSON array.
   */
  static fromPackedLeaves(depth: number, packedLeaves: Buffer): IndexedMerkleTree
  root(): string
  /** Return the root as one canonical 32-byte big-endian field element. */
  rootPacked(): Buffer
  get leafCount(): number
  /**
   * Advance the tree transactionally: the live tree changes only after all
   * insertions, sibling proofs, and the circuit input hash succeed.
   */
  buildPendingCommitment(batchSize: number, pendingNoteIdsJson: string): PendingCommitmentInput
  /**
   * Packed counterpart to `buildPendingCommitment`. Each pending note id is
   * a canonical 32-byte big-endian BN254 field element.
   */
  buildPendingCommitmentPacked(batchSize: number, pendingNoteIds: Buffer): PendingCommitmentInput
}

/**
 * HAWK resident prover. Circuit identity and dimensions come only from the
 * authenticated witness graph and zkey, so the same API serves every Circom
 * circuit accepted by `curvy-prover`.
 */
export declare class ResidentProver {
  constructor(options: ResidentProverOptions)
  /**
   * Authenticate and parse both artifacts on a native task instead of the
   * JavaScript event loop. The constructor is available when deliberately
   * synchronous startup is preferable.
   */
  static create(options: ResidentProverOptions): Promise<ResidentProver>
  get artifactLoadMs(): number
  get artifactInitializationMs(): number
  get numConstraints(): number
  get numPublic(): number
  get threads(): number
  get mode(): string
  get profile(): string
  get witnessBackend(): string
  /**
   * SHA-256 of the loaded key's verifying key. Compare it against the
   * deployed verifier before submitting proofs.
   */
  get verifyingKeyDigest(): string
  get r1csSha256(): string
  prove(inputJson: string): Promise<ProofResult>
}

export interface PendingCommitmentInput {
  circuitInputJson: string
  inputHash: string
  paddedNoteIds: Array<string>
  newNotesRoot: string
}

export interface ProofResult {
  proofJson: string
  publicSignalsJson: string
  witnessCalculationMs: number
  proofGenerationMs: number
}

export interface ResidentProverOptions {
  zkeyPath: string
  zkeySha256: string
  witnessGraphPath?: string
  witnessGraphSha256: string
  /** Compile SIGNET to SAGE on initialization. Defaults to false. */
  useSage?: boolean
  /**
   * An authenticated precompiled SAGE program. Both path and digest are
   * required; witnessGraphSha256 still pins the original SIGNET source.
   */
  sageProgramPath?: string
  sageProgramSha256?: string
  /** Independently pinned chunk manifest for one-pass resident key loading. */
  zkeyManifestPath?: string
  zkeyManifestSha256?: string
  /**
   * Number of Rayon workers used by this prover. Defaults to one so a
   * backend cannot accidentally consume every host core.
   */
  threads?: number
  /**
   * Maximum accepted proofs, including the running proof. Defaults to 8;
   * excess requests reject immediately. Must be between 1 and 64.
   */
  maxPendingProofs?: number
}

export declare function rsCoreVersion(): string
