/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Artifact-driven native prover. Circuit identity and dimensions come only
 * from the authenticated witness graph and zkey, so the same API serves every
 * Circom circuit accepted by `curvy-prover`.
 */
export declare class CircuitProver {
  constructor(options: CircuitProverOptions)
  get artifactLoadMs(): number
  get artifactInitializationMs(): number
  get numConstraints(): number
  get numPublic(): number
  get threads(): number
  get r1csSha256(): string
  prove(inputJson: string): Promise<ProofResult>
}

/**
 * Native indexed Poseidon tree used by backend services. The tree itself is a
 * core primitive; `build_pending_commitment` is the canonical adapter for the
 * currently deployed pending-notes-commitment circuit input.
 */
export declare class IndexedMerkleTree {
  constructor(depth: number, leavesJson: string)
  root(): string
  get leafCount(): number
  /**
   * Advance the tree transactionally: the live tree changes only after all
   * insertions, sibling proofs, and the circuit input hash succeed.
   */
  buildPendingCommitment(batchSize: number, pendingNoteIdsJson: string): PendingCommitmentInput
}

export interface CircuitProverOptions {
  zkeyPath: string
  zkeySha256: string
  witnessGraphPath: string
  witnessGraphSha256: string
  /**
   * Number of Rayon workers used by this prover. Defaults to one so a
   * backend cannot accidentally consume every host core.
   */
  threads?: number
}

export interface PendingCommitmentInput {
  circuitInputJson: string
  inputHash: string
  paddedNoteIds: Array<string>
  newNotesRoot: string
}

export interface ProofResult {
  proofJson: string
  publicSignalsJson: string
  witnessCalculationMs: number
  proofGenerationMs: number
}

export declare function rsCoreVersion(): string
