/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Installed by index.js; both delegate to `close()`. */
export interface ResidentProver {
  /** `using`: starts `close()` without waiting for the release. */
  [Symbol.dispose](): void
  /** `await using`: resolves once `close()` has released the key. */
  [Symbol.asyncDispose](): Promise<void>
}

/**
 * Native indexed Poseidon tree used by backend services. The tree itself is a
 * core primitive; `build_pending_commitment` is the canonical adapter for the
 * currently deployed pending-notes-commitment circuit input.
 */
export declare class IndexedMerkleTree {
  constructor(depth: number, leavesJson: string)
  /**
   * Construct directly from concatenated canonical 32-byte big-endian
   * BN254 field elements, avoiding decimal strings and a JSON array.
   */
  static fromPackedLeaves(depth: number, packedLeaves: Buffer): IndexedMerkleTree
  root(): string
  /** Return the root as one canonical 32-byte big-endian field element. */
  rootPacked(): Buffer
  get leafCount(): number
  /**
   * Advance the tree transactionally: the live tree changes only after all
   * insertions, sibling proofs, and the circuit input hash succeed.
   */
  buildPendingCommitment(batchSize: number, pendingNoteIdsJson: string): PendingCommitmentInput
  /**
   * Packed counterpart to `buildPendingCommitment`. Each pending note id is
   * a canonical 32-byte big-endian BN254 field element.
   */
  buildPendingCommitmentPacked(batchSize: number, pendingNoteIds: Buffer): PendingCommitmentInput
}

/**
 * Constant-space frontier of the notes tree: the completed subtrees along its
 * right-hand edge, at most one per level, and the leaf count.
 *
 * It appends leaves and builds the pending-notes-commitment circuit input
 * exactly as [`IndexedMerkleTree`] does, but holds no leaf, so its size does
 * not depend on how many notes the tree contains (a depth-30 snapshot is at
 * most 1,015 bytes). A prover that only ever appends needs nothing more.
 *
 * Two things it cannot do, because it has forgotten the leaves: prove that an
 * earlier leaf is in the tree, and notice that a note id is already in it.
 * Only a repeat inside one batch is rejected here.
 */
export declare class NotesFrontier {
  /**
   * An empty frontier. `shardHeight` must match whoever else reads the
   * snapshot; it does not affect roots or commitment inputs.
   */
  constructor(depth: number, shardHeight: number)
  /** An empty frontier with the production notes-tree geometry. */
  static production(): NotesFrontier
  /**
   * Restore a frontier from `snapshot()` bytes. The indexer stores the same
   * format with each block, so a prover can start from the block whose root
   * the chain has instead of replaying every leaf.
   */
  static fromSnapshot(snapshot: Buffer): NotesFrontier
  /** The canonical versioned snapshot of this frontier. */
  snapshot(): Buffer
  root(): string
  /** Return the root as one canonical 32-byte big-endian field element. */
  rootPacked(): Buffer
  get leafCount(): number
  /**
   * Depth of the tree this frontier belongs to. A restored snapshot carries
   * its own, so check it against the depth the caller expects.
   */
  get depth(): number
  /**
   * Append leaves in order, all or none. This is how a frontier is rebuilt
   * from the committed notes, a page at a time, when no snapshot is at hand.
   */
  append(leavesJson: string): void
  /**
   * Packed counterpart to `append`. Each leaf is a canonical 32-byte
   * big-endian BN254 field element.
   */
  appendPacked(leaves: Buffer): void
  /**
   * Advance the frontier transactionally and return the same circuit input
   * `IndexedMerkleTree.buildPendingCommitment` returns for the same tree
   * and notes. Take `snapshot()` first to be able to go back if the commit
   * built from this input does not land.
   */
  buildPendingCommitment(batchSize: number, pendingNoteIdsJson: string): PendingCommitmentInput
  /**
   * Packed counterpart to `buildPendingCommitment`. Each pending note id is
   * a canonical 32-byte big-endian BN254 field element.
   */
  buildPendingCommitmentPacked(batchSize: number, pendingNoteIds: Buffer): PendingCommitmentInput
}

/**
 * HAWK resident prover. Circuit identity and dimensions come only from the
 * authenticated witness graph and zkey, so the same API serves every Circom
 * circuit accepted by `curvy-prover`.
 */
export declare class ResidentProver {
  constructor(options: ResidentProverOptions)
  /**
   * Authenticate and parse both artifacts on a native task instead of the
   * JavaScript event loop. The constructor is available when deliberately
   * synchronous startup is preferable.
   */
  static create(options: ResidentProverOptions): Promise<ResidentProver>
  get artifactLoadMs(): number
  get artifactInitializationMs(): number
  get numConstraints(): number
  get numPublic(): number
  get threads(): number
  get mode(): string
  get profile(): string
  get witnessBackend(): string
  /**
   * SHA-256 of the loaded key's verifying key. Compare it against the
   * deployed verifier before submitting proofs.
   */
  get verifyingKeyDigest(): string
  get r1csSha256(): string
  /** True once `close()` has been called. */
  get closed(): boolean
  prove(inputJson: string): Promise<ProofResult>
  /**
   * Stop accepting proofs and release the native key and worker pool.
   * Proofs accepted before `close()` still settle normally; the promise
   * resolves once the last of them has finished and both are freed. Later
   * `prove()` calls reject with `prover is closed`; metadata getters keep
   * returning the values captured at load. Repeated calls are no-ops that
   * resolve at the same point.
   */
  close(): Promise<void>
}

export interface PendingCommitmentInput {
  circuitInputJson: string
  inputHash: string
  paddedNoteIds: Array<string>
  newNotesRoot: string
}

export interface ProofResult {
  proofJson: string
  publicSignalsJson: string
  witnessCalculationMs: number
  proofGenerationMs: number
}

export interface ResidentProverOptions {
  zkeyPath: string
  zkeySha256: string
  witnessGraphPath?: string
  witnessGraphSha256: string
  /** Compile SIGNET to SAGE on initialization. Defaults to false. */
  useSage?: boolean
  /**
   * An authenticated precompiled SAGE program. Both path and digest are
   * required; witnessGraphSha256 still pins the original SIGNET source.
   */
  sageProgramPath?: string
  sageProgramSha256?: string
  /** Independently pinned chunk manifest for one-pass resident key loading. */
  zkeyManifestPath?: string
  zkeyManifestSha256?: string
  /**
   * Number of Rayon workers used by this prover. Defaults to one so a
   * backend cannot accidentally consume every host core.
   */
  threads?: number
  /**
   * Maximum accepted proofs, including the running proof. Defaults to 8;
   * excess requests reject immediately. Must be between 1 and 64.
   */
  maxPendingProofs?: number
  /**
   * Accept artifacts up to the batch-prover budget (8,000,000 graph nodes,
   * a 96 MiB graph) instead of the client budget (2,000,000 nodes, 64 MiB).
   * The 20- and 50-note pending-commitment circuits need it. Defaults to
   * false, so a process that never loads those circuits does not widen what
   * it will allocate for an artifact.
   */
  batchProfile?: boolean
}

export declare function rsCoreVersion(): string
